### ISSUE TITLE
Typo in chialisp-web/docs/coins_spends_and_wallets.md

### ISSUE THREAD

**Issue by BrandtH22** [Chia-Network/chialisp-web#102]
I believe there is a type in chialisp-web/docs/coins_spends_and_wallets.md on line 101:
"ASSERT_MY_PUZZLE_HASH - [72]" should be "ASSERT_MY_PUZZLEHASH - [72]"

 - Sorry to nitpick but ran across it while setting up a syntax highlighter.
 Make it an excellent evening!

**Comment by Quexington** [comment]
This should be fixed in #104, thanks for pointing it out!
