### ISSUE TITLE
chialisp.com landing page is currently referencing old/misleading video content

### ISSUE THREAD

**Issue by rwarren** [Chia-Network/chialisp-web#107]
The landing page currently lists an old (and no longer correct) video from 2020 as "_A video introduction to developing in Chialisp_". From experience, I can state that this is misleading and a bit frustrating. :)

It would probably be better would be to link the more current videos that are on these pages:
* https://chialisp.com/docs/tutorials/developing_applications
* https://chialisp.com/docs/tutorials/programming_chialisp
* and others in that tutorial tree!

**Comment by Quexington** [comment]
Should be fixed on #108 thanks!
