### ISSUE TITLE
run doc example code get error

### ISSUE THREAD

**Issue by arlicle** [Chia-Network/chialisp-web#28]
brun '(* (q . 2) (q . 4) (q . 5))' '()'
FAIL: rest of non-cons 5

brun '(* (q . 2) (q . 4) (q . 5))' '()'
FAIL: rest of non-cons 5

brun '(+ (q . 10) (q . 20) (q . 30) (q . 40))' '()'
FAIL: rest of non-cons 40

**Comment by arlicle** [comment]
brun '(a (i (q . 0) (q . (x (q . 1337) )) (q . 1)) ())'
FAIL: env requires no parameters (a (i (q) (q 9 (q . 1337)) (q . 1)) ())

**Comment by Quexington** [comment]
This works for me, it may be something wrong with your clvm_tools installation.  Try to install it again.

> 
> 
> brun '(* (q . 2) (q . 4) (q . 5))' '()'
> FAIL: rest of non-cons 5
> 
> brun '(* (q . 2) (q . 4) (q . 5))' '()'
> FAIL: rest of non-cons 5
> 
> brun '(+ (q . 10) (q . 20) (q . 30) (q . 40))' '()'
> FAIL: rest of non-cons 40

This doesn't fail for me either, but it does need some changing to make it work properly.

> 
> 
> brun '(a (i (q . 0) (q . (x (q . 1337) )) (q . 1)) ())'
> FAIL: env requires no parameters (a (i (q) (q 9 (q . 1337)) (q . 1)) ())

**Comment by Quexington** [comment]
This gets fixed in https://github.com/Chia-Network/chialisp-web/pull/55
