### ISSUE TITLE
MonsterSprouts link goes to 404

### ISSUE THREAD

**Issue by RightSexyOrc** [Chia-Network/chialisp-web#288]
from this page 

https://github.com/Chia-Network/chialisp-web/blob/main/docs/primitives/cats.md

**Comment by hoffmang9** [comment]
Looks like we made that repo private. We'll get to the bottom of it.

**Comment by RightSexyOrc** [comment]
bump

**Comment by BrandtH22** [comment]
Regarding the monster sprouts repo, we will be removing all links to it on our other repos. It was made private due to a security issue with a dependency and as of now we do not have plans to resolve those and make the repo functional. Was there something specific you were trying to get from it?

**Comment by BrandtH22** [comment]
this will be resolved in #296
