### ISSUE TITLE
Redirect to CLVM glossary is broken on basics webpage

### ISSUE THREAD

**Issue by corydickson** [Chia-Network/chialisp-web#52]
When navigating `https://chialisp.com/docs/` in the Basics subsection the reference link to the glossary at the top of the page redirects to `https://chialisp.com/docs/ref/clvm/` but at the bottom page under the "End of Section 1" the link to the same webpage is broken `https://chialisp.com/docs/chialisp.com/docs/ref/clvm`

Locally, line 361 on `docs/basics.md` redirects correctly but is missing the exclamation mark.

**Comment by Quexington** [comment]
This seems to be fixed on the current version of the website.  If it's still broken for you, maybe try clearing your cache or opening in incognito?
