### ISSUE TITLE
Inner Outer example - MOD_HASH explanation unclear

### ISSUE THREAD

**Issue by geraldneale** [Chia-Network/chialisp-web#86]
https://chialisp.com/docs/common_functions#outer-and-inner-puzzles
keybase://chat/chia_network.public#chialisp/6660

As per Quexington in the above Keybase discussion, MOD_HASH is a tree hash of the example code _with no curried arguments._ This is relevant point to understanding the example, getting it to run and is unclear in the documentation due to omission.

Please consider changing  the following from:
"MOD_HASH which is the tree hash of this code"

To:
"MOD_HASH which is the tree hash of this code _with no curried arguments_"

**Comment by Quexington** [comment]
This has been resolved in #88 thanks!
